Monumentpage
wJoenn/artify pull request #119
Opened 2023-03-21 15:41 UTC by AntonioDannemann

created show page for monument, created stimulus controller to expand and retract the div .glass_container to display the full info of the monument

2023-03-21 15:51 UTC, Glod33 commented
Hey man:)

Could you add a screenshot or a video for me.

2023-03-21 15:53 UTC, AntonioDannemann commented
hey! actually I just want to push, so that Louis could help me with something, but yeah I will share a video, so just don't approve the merge
https://user-images.githubusercontent.com/112712290/226665401-16fd6966-0451-4307-a258-a926817ad682.mov

2023-03-21 16:16 UTC, wJoenn requested changes
Locked for now

2023-03-23 23:38 UTC, AntonioDannemann commented
Here is the last changes made

https://user-images.githubusercontent.com/112712290/227387604-20dfcb2d-8d9a-49f2-b9d4-364d0b5b0591.mov

2023-03-24 13:09 UTC, AntonioDannemann commented
new style for the monument show page and the history show page

https://user-images.githubusercontent.com/112712290/227529707-0edcbe22-c3df-4c4f-b6f7-f992d36746a3.mov

2023-03-24 14:01 UTC, wJoenn requested changes

2023-03-24 14:01 UTC, wJoenn commented on app/assets/stylesheets/monuments/_show.scss
> +      }
please remove the height, the picture will then keep it's initial aspect ratio which makes more sense.
Remove the empty line at l:92 too

2023-03-24 17:12 UTC, AntonioDannemann commented on app/assets/stylesheets/application.scss
>  @import "components/index";
done

2023-03-24 17:13 UTC, AntonioDannemann commented on app/controllers/histories_controller.rb
> +    @monuments = Monument.where(city: @history.monument.city).where.not(id: @history.monument.id)
done

2023-03-24 17:15 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +      <p class="truncate" data-glass-container-target="truncate"><%= @monument.description.split(". ").first(2).join(". ") %></p>
done

2023-03-24 17:16 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +        <p><%= subarray.join(". ") %></p>
done

2023-03-24 17:26 UTC, AntonioDannemann commented on app/javascript/controllers/glass_container_controller.js
> +  }
done

2023-03-24 17:29 UTC, AntonioDannemann commented on app/javascript/controllers/glass_container_controller.js
> +  }
done

2023-03-24 17:35 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +  </div>
done

2023-03-24 17:39 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +      <h4><%= @monument.name %></h4>
done

2023-03-24 17:39 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +      </div>
done

2023-03-24 17:40 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +      </div>
done

2023-03-24 17:55 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +      <% @monument.description.split(". ")[2..].each_slice(3).map do |subarray| %>
done

2023-03-24 17:56 UTC, AntonioDannemann commented on app/assets/stylesheets/monuments/_show.scss
> +  background-position: center;
done

2023-03-24 17:57 UTC, AntonioDannemann commented on app/assets/stylesheets/monuments/_show.scss
> +    }
done

2023-03-24 18:03 UTC, AntonioDannemann commented on app/assets/stylesheets/monuments/_show.scss
> +        }
done! good to know!

2023-03-24 18:04 UTC, AntonioDannemann commented on app/assets/stylesheets/monuments/_show.scss
> +      }
done

2023-03-24 18:04 UTC, AntonioDannemann commented on app/assets/stylesheets/monuments/_show.scss
> +      }
done

2023-03-24 18:05 UTC, AntonioDannemann commented on app/assets/stylesheets/monuments/_show.scss
> +      }
done

2023-03-24 18:20 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> -<h1>Histories#show</h1>
done

2023-03-24 23:05 UTC, wJoenn requested changes

2023-03-24 23:05 UTC, wJoenn commented on app/javascript/controllers/glass_container_controller.js
> +  }
You only have one truncate target so why are you doing `truncateTargets.forEach` instead of `truncateTarget.classList.toggle("truncate")` ?

Beside, you don't need the if statement because think about it, if the glass is shrinked it will already be scrolled at the top so clicking won't change that.

2023-03-24 23:05 UTC, wJoenn commented on app/javascript/controllers/glass_container_controller.js
> +    }
Same, you only have one truncate target so why are you doing truncateTargets.forEach instead of truncateTarget.classList.toggle("truncate") ?

2023-03-24 23:05 UTC, wJoenn commented on app/views/monuments/show.html.erb
> +<%= render partial: "shared/show", locals: { photo_key: @monument.photo.key } %>
You don't need to specifiy partial and locals, you can do
`<%= render "shared/show", photo_key: @monument.photo.key %>`
instead

2023-03-24 23:05 UTC, wJoenn commented on app/views/histories/show.html.erb
> +<%= render partial: "shared/show", locals: { photo_key: @history.photo.key } %>
You don't need to specifiy partial and locals, you can do
`<%= render "shared/show", photo_key: @monument.photo.key %>`
instead

2023-03-24 23:05 UTC, wJoenn commented on app/views/shared/_show.html.erb
> +      <%= @first_para %>.</p>
This should be one line

2023-03-25 08:18 UTC, AntonioDannemann commented on app/controllers/histories_controller.rb
> +    @first_para = paragraphs.shift(2).join(". ")
done

2023-03-25 08:20 UTC, AntonioDannemann commented on app/controllers/monuments_controller.rb
> +    @monuments = Monument.where(city: @monument.city)
done

2023-03-25 08:20 UTC, AntonioDannemann commented on app/controllers/monuments_controller.rb
> +    @first_para = paragraphs.shift(2).join(". ")
done

2023-03-25 08:31 UTC, AntonioDannemann commented on app/javascript/controllers/glass_container_controller.js
> +  }
done

2023-03-25 08:32 UTC, AntonioDannemann commented on app/javascript/controllers/glass_container_controller.js
> +    }
done

2023-03-25 08:34 UTC, AntonioDannemann commented on app/views/monuments/show.html.erb
> +<%= render partial: "shared/show", locals: { photo_key: @monument.photo.key } %>
done

2023-03-25 08:34 UTC, AntonioDannemann commented on app/views/histories/show.html.erb
> +<%= render partial: "shared/show", locals: { photo_key: @history.photo.key } %>
done

2023-03-25 08:35 UTC, AntonioDannemann commented on app/views/shared/_show.html.erb
> +      <%= @first_para %>.</p>
done

2023-03-25 08:40 UTC, wJoenn approved these changes

2023-03-25 08:40 UTC, merged