Nearby v3
wJoenn/artify pull request #121
Opened 2023-03-21 15:49 UTC by Glod33

See slack for comments

2023-03-22 14:40 UTC, Glod33 commented
Ready for review

2023-03-22 15:17 UTC, wJoenn commented
As I said on slack, the page isn't working on mobile.
The images are way too heavy to load and atm we only have 40, imagine what would happen if we had hundreds of monuments to display ?

2023-03-22 15:18 UTC, wJoenn commented
Also I don't know if the doge is a joke you forgot to remove or something but that shouldn't be in the final product 😅

2023-03-22 15:55 UTC, Glod33 commented
In that case they can be these dots but styled, like a pin for instance. 

I think the list can stay then as it renders only what's in view and there can be a limit of how much and a zoom restriction.

I thought the doge would be a funny thing to add, but i'll remove it if you want.

<img width="1105" alt="Screenshot 2023-03-22 at 16 52 53" src="https://user-images.githubusercontent.com/112162648/226963213-f8a89e8c-8afc-4dd0-8231-6c2b6d02eb79.png">

2023-03-22 16:00 UTC, wJoenn commented
Imo the best solution would be to clickable pins that reveal the list with the clicked monument either in the middle of the list or in full width then as soon as you start moving again on the map the list disappears.
The cards would then be the link to the show page instead of the pin

2023-03-22 16:14 UTC, Glod33 commented
The images are now dropped to the lowest quality does this improve things?

2023-03-22 16:54 UTC, Glod33 commented
Have you allowed location tracking?

I wonder if the popups are loaded upon the loading of the map though and I am not sure how to check that without re-adding a lot of code.

If you want to handle a map with a lot of markers it would in any case require a lot more and I don't think there is the time to do that so I'd say we fake it.

2023-03-22 16:57 UTC, Glod33 commented
One thing I can also check is if I can make the map be scrollable only within a certain zoom, but I don't know if that is possible.

2023-03-22 17:15 UTC, wJoenn commented
I believe I have 🤔 
Just in case I checked in another browser where I was prompted to allow and I did so either I refused with my browser or it's not compatible.
Have you tried it on your mobile ? Does it work ?

2023-03-24 11:40 UTC, Glod33 commented
I would just like to add my custom marker, but I don't know how and can't figure it out.

2023-03-24 11:42 UTC, Glod33 commented
<img width="407" alt="Screenshot 2023-03-24 at 12 41 51" src="https://user-images.githubusercontent.com/112162648/227512251-89c5ac82-d209-4481-ac61-d892e1c046e5.png">

2023-03-24 11:43 UTC, Glod33 commented
Also I am aware of a bug that refuses to locate my location on NGROK, I'll ask a TA about that unless Louis knows why that happens.

2023-03-24 12:40 UTC, wJoenn commented
I don't have such issue with my phones on ngrok.

Can we have a video please ?

2023-03-24 13:15 UTC, Glod33 commented
Alright, that would mean that the markers won't have an image, 

https://user-images.githubusercontent.com/112162648/227531124-b335eea5-9e89-41ab-9b70-273563a2fe52.mov

2023-03-25 12:04 UTC, Glod33 commented
The icon not aligning with the hitbox is a mapbox bug sadly, I couldn't find a fix for that.

I think it's ready for merging, although I'd like to add the distance between but don't know how.

2023-03-25 17:43 UTC, wJoenn requested changes

2023-03-25 17:43 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +    padding: 5px 0;
You can remove justify content, width, height, color, margin and padding

2023-03-25 17:43 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +    }
You can remove the width and add a flex grow of 1 and a margin of 0

Then instead of limiting this to 20 words you can truncate it by adding
```
overflow: hidden;
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 8;
```

2023-03-25 17:43 UTC, wJoenn commented on app/assets/stylesheets/monuments/_index.scss
>  }
You're not using this class anywhere, you can remove it.

2023-03-25 17:43 UTC, wJoenn commented on app/assets/stylesheets/monuments/_index.scss
> +}
It makes more sense to do the opposite.

First thing first remove the bottom and the height from the listing expanded
Then add a max-height of 0, a padding of 0 10px and an opacity of 0

Then for the listing remove the left, the width, the display, the align-items and the padding-top
Then change the bottom to 0, the height to max-content, the padding to 23px 10px 10px, the background color to #181a1b80, the backdrop filter to 10px
Then add a max-height of 285px, and an overflow of hidden

Finally, change the name of your listing-expanded to listing-hidden and in your javascript remove it instead of adding it

2023-03-25 17:43 UTC, wJoenn commented on app/views/monuments/show.html.erb
> +<%= image_tag 'location_pin' %>
Remove any changes you've made to this file please

2023-03-25 17:43 UTC, wJoenn commented on config/environments/development.rb
> +  config.hosts << "e351-2a02-a465-dba3-1-2c4a-2207-50e6-73da.eu.ngrok.io"
You can change that to
config.hosts.clear that way we stop sharing our IP address 😄

2023-03-25 17:43 UTC, wJoenn commented on app/views/monuments/index.html.erb
> +  </div>
These two should have 1 line each

2023-03-25 17:43 UTC, wJoenn commented on app/views/monuments/_card_index.html.erb
> +    <p class="desc-short"> <%= mon.description.split.first(20).join(" ") %>...</p>
If you added the truncate in the css like I showed then you don't need to edit the description anymore

2023-03-25 17:43 UTC, wJoenn commented on app/views/monuments/show.html.erb
> +<%= image_tag 'location_pin' %>
That'll also fix your conflict

2023-03-26 09:26 UTC, Glod33 commented on app/assets/stylesheets/components/_button.scss
> +  position: sticky;
Because of that issue with the navbar being below it, it at least keeps it in that spot now if that happens

2023-03-26 09:33 UTC, Glod33 commented on app/assets/stylesheets/components/_card.scss
> +    padding: 5px 0;
I could only delete: height, color, margin and padding.
Width and justify content are necesary

2023-03-26 09:37 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +    padding: 5px 0;
I tested everything in my browser and if if you apply all the changes I said it should work. It did for me

2023-03-27 12:06 UTC, wJoenn requested changes

2023-03-27 12:06 UTC, wJoenn commented on app/javascript/controllers/map_controller.js
> +      });
You can move this.#flyMapToUser inside the second getCurrentPosition that way you only have one navigator active.

You should be able to remove the parenthesis around the e in line 21 and can you rename it event for readability sake please ?

If you remove the listing-hidden after the innerHTML has been updated that means you don't need to empty it first.
To do that simply remove the innerHTML = "" in line 24 the move the remove("listing-hidden") in the then(html => after innerHTML = html

2023-03-27 18:41 UTC, Glod33 commented on app/javascript/controllers/map_controller.js
> +      });
I don't understand what you mean with the last part

2023-03-27 18:57 UTC, wJoenn commented on app/javascript/controllers/map_controller.js
> +      });
Sorry. What I mean is remove line 24 and move line 23 to between line 31 and 32.
That means that when you click on a monument you first fetch the monument, update the HTML then show the card.
Instead of showing the card first but then have to wait some micro seconds for the content to actually appear.
It's not very noticeable but it does create a flashing effect when content is update after you show the element

2023-03-27 20:44 UTC, merged