User dashboard
wJoenn/artify pull request #123
Opened 2023-03-22 00:47 UTC by MarianaCarlota

![image](https://user-images.githubusercontent.com/114437310/226773419-590dc541-6abf-49da-bfb9-f1794c4ad10a.png)
![image](https://user-images.githubusercontent.com/114437310/226773484-92c2a2f9-be84-4c68-ae7e-ff1841681aee.png)

2023-03-22 11:57 UTC, wJoenn commented
As I said in DM
The idea is great. I do think some changes should be made though

There should be a home button on the top left like on the other pages

If both the edit button and the gear button do the same thing then I would remove the edit button and style the gear to be the same as the home button

Your title "My Monuments" look like a button which doesn't really make sense, "My monuments" isn't very fitting either because you're also showing achievements and the monuments aren't the user's to begin with. I would rename that "My profile" or "Your profile" or maybe not use a title a all ?

I think there shouldn't be a camera button in here if we have a button to go to the homepage already

The achievement progression looks very nice but I think it should stick with the rest of the achievement part instead of having achievements related stuff at the begining and at the end with something in the middle

I also think it's be nice to have more than one "in progress" achievement showing

Can you remove the "favourite" section from the dashboard for now ? The feature doesn't exist yet and I'd like Antonio to add it to this page once he's ready to do so.

The achievement sections look great but for the same reason i'd like you to remove them for now and we'll add them back when the time comes

I don't think the footer is necessary on this page

2023-03-22 14:19 UTC, Glod33 commented
I really like it:)
I also agree with what Louis said but would only add perhaps rounding the green profile part would make it look a little bit more playful.

2023-03-22 21:23 UTC, MarianaCarlota commented
This is what we have now. Favourites and achievements will be added when those sections are finished

![image](https://user-images.githubusercontent.com/114437310/227041367-a0880677-daa3-4291-9f4a-71c24d5573f9.png)

2023-03-22 22:54 UTC, wJoenn requested changes
Can you remove all the pictures except the one you kept in the dashboard please ?

2023-03-22 22:54 UTC, wJoenn commented on app/controllers/users_controller.rb
> +  end
You don't need a new History now and your @monuments should be the histories of the user only, not all the monuments

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_index.scss
> +@import "dashboard";
Your dashboard should be `stylesheets/users/_dashboard.scss`, not a component

2023-03-22 22:54 UTC, wJoenn commented on app/views/users/dashboard.html.erb
> +  </div>
I'm guessing you're wrapping this button inside a div but you don't need to because it has a position of fixed to the top right corner.

2023-03-22 22:54 UTC, wJoenn commented on app/views/users/dashboard.html.erb
> +    </div>
These 2 divs have no purpose, you can remove them and leave the anchor and the image without wrappers

2023-03-22 22:54 UTC, wJoenn commented on app/views/users/dashboard.html.erb
> +</div>
The #mu-monuments div does nothing, you can remove it

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +
Why create a new card-dahsboard class instead of using the existing card-monument ?

2023-03-22 22:54 UTC, wJoenn commented on app/views/users/components/_achievements.html.erb
> +<section id="nearby">
You can remove this file

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +  border-bottom-right-radius: 16px;
User border-radius: 0 0 16px 10px; instead
Why are you using 2 different border radius instead of the same ?
I wouldn't even use a border radius here tbh 🤔 

Also what's the point of the background-size if you don't use a border-image ?

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +  }
You don't need this, the home button has a fixed position

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +      flex: 1 0 auto;
You can use flex-grow: 1; instead

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +      }
Move the color to the .welcome-message and add the margin 0 to
```
* {
 margin: 0;
 }
```
 instead of to each element.
 Using * means every element, so .welcome-message * means all the element inside the welcome-message

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +    }
Are you sure you need the overflow hidden and the margin 0 auto ? 🤔

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +    }
What's the point of the margin 0 auto ? You overwrite it with margin 8px
Why do you need margin 8px ? Your .profile-bottom should be handling the spacing with padding and gap instead

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +  }
You can remove this the color of the btn-home is already green

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_button.scss
> +}
You can remove this

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_button.scss
> +}
You don't need to rewrite the whole thing.
Just give this a background-color and a color of lightgrey then give both this class and the btn-main to your element

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +  }
Why do you have 2 card-dashboard ?

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_dashboard.scss
> +}
You can remove all of this

2023-03-22 22:54 UTC, wJoenn commented on app/assets/stylesheets/components/_banner.scss
> +#user-banner {
This whole thing should be inside your _dashboard.scss

2023-03-23 21:43 UTC, wJoenn commented on app/controllers/users_controller.rb
> +  end
You don't want all the histories, you want all the histories of the current_user

2023-03-23 21:44 UTC, wJoenn commented on app/views/users/components/_achievements.html.erb
> +<section id="nearby">
This file can be removed as the achievements are not included in this PR

2023-03-23 21:45 UTC, wJoenn commented on app/views/histories/index.html.erb
> +<section id="nearby">
Can you share a screenshot of this page please ?

But as I told you, this is another issue and should be in another branch and another PR.
This PR is already big enough 😅

2023-03-23 21:53 UTC, wJoenn commented on app/assets/stylesheets/users/_dashboard.scss
> +    }
Why do you need a margin 0 auto and a overflow hidden ?

2023-03-23 22:42 UTC, MarianaCarlota commented on app/views/histories/index.html.erb
> +<section id="nearby">
You are right. Sorry 🙃

2023-03-23 22:44 UTC, wJoenn commented on app/views/histories/index.html.erb
> +<section id="nearby">
No worries 🙂

2023-03-23 22:56 UTC, wJoenn commented on app/assets/stylesheets/users/_dashboard.scss
> +  }
Maybe you were overwritting the green with a darkgrey so you had to overwrite it again with green.
Does it work now if you remove it ?

2023-03-23 23:09 UTC, MarianaCarlota commented on app/assets/stylesheets/users/_dashboard.scss
> +  border-bottom-right-radius: 16px;
the border-radius is a mistake. The padding, I want more on top because of the btn-home

2023-03-23 23:11 UTC, wJoenn commented on app/assets/stylesheets/users/_dashboard.scss
> +  border-bottom-right-radius: 16px;
Ok
For border radius you can do `border-radius: 0 0 10px 10px;`

2023-03-23 23:12 UTC, MarianaCarlota commented on app/assets/stylesheets/users/_dashboard.scss
> +    }
I just tried without it now and it's looking the same. it's removed now

2023-03-23 23:14 UTC, MarianaCarlota commented on app/assets/stylesheets/users/_dashboard.scss
> +  }
now it works, yes. probably it was because it was inside the same div as the gear and it overwrote the color, yes. I removed it now.

2023-03-23 23:34 UTC, wJoenn requested changes

2023-03-23 23:34 UTC, wJoenn commented on app/assets/stylesheets/users/_dashboard.scss
> +  border-bottom-right-radius: 16px;
This can be written as `border-radius: 0 0 16px 16px;`

2023-03-23 23:34 UTC, wJoenn commented on app/assets/stylesheets/users/_dashboard.scss
> +    }
Please change this to
```
    .welcome-message {
      flex-grow: 1;
      color: $darkgrey;

      * {
        margin: 0px;
      }

      h2 {
        font-size: 2.2rem;
      }
    }
```

2023-03-23 23:34 UTC, wJoenn commented on app/controllers/users_controller.rb
> +end
You forgot to correct this.
You don't want all the histories, only the histories of the current_user

2023-03-24 21:19 UTC, wJoenn requested changes

2023-03-24 21:19 UTC, wJoenn commented on app/controllers/users_controller.rb
> +    @histories = History.where(user: current_user)
There's still one thing left, we want the histories to be ordered form the newest to the latest by by default they will be ordered with the latests firsts. Can you change that please ? 🙂

2023-03-24 21:32 UTC, wJoenn approved these changes

2023-03-24 21:32 UTC, merged