Log out button
wJoenn/artify pull request #168
Opened 2023-03-25 23:19 UTC by MarianaCarlota

I putted it in the edit page. In the dashboard it was not looking good. I also added a button to go back. it didn't had one.

![image](https://user-images.githubusercontent.com/114437310/227746930-4a58c2b0-825f-4f8a-b910-a752ad4d7013.png)

2023-03-25 23:32 UTC, wJoenn requested changes

2023-03-25 23:32 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +    </div>
Remove the div and include the icon inside the link please

2023-03-25 23:32 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +    <% end %>
You could be using the same back button as for the other forms for consistency

2023-03-26 10:00 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +    <% end %>
but I am. Isn't it this one?

2023-03-26 10:05 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +    <% end %>
![image](https://user-images.githubusercontent.com/114437310/227768708-f824a41f-7663-471c-837f-babcd2cb1032.png)

2023-03-26 10:12 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +    </div>
I'm getting this error. What am I donig wrong?

![image](https://user-images.githubusercontent.com/114437310/227768981-54e03dc7-510c-4811-8992-5095c48b0be6.png)

2023-03-26 10:28 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +    <% end %>
oh, the other forms, you mean. Sure we can keep that one

2023-03-26 13:46 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +    </div>
You need to remove the "Log Out" and move it inside the do end

2023-03-26 15:18 UTC, wJoenn approved these changes

2023-03-26 15:18 UTC, merged