Generated UserFavouriteMonument model
wJoenn/artify pull request #183
Opened 2023-03-26 21:49 UTC by AntonioDannemann

created, model, reference to user and monument, created controller

2023-03-26 22:00 UTC, wJoenn requested changes

2023-03-26 22:00 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
`current_user.favourites.includes(:monument)` is not how you find traditionnaly select instances of favourites where the user is the current_user

2023-03-26 22:00 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +    @favourite = current_user.favourites.build(monument: @monument)
`current_user_favourites.build` is not how you initialized a new instance of Favourite

2023-03-26 22:00 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +    end
You don't need a notice or an alert because the icon of favourite will change colour if it is favourite so that will let the user know if it worked or not

2023-03-26 22:00 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
You don't need a notice because the icon will change colour

2023-03-26 22:00 UTC, wJoenn commented on app/models/favorite.rb
> +end
Please rename to Favourite

belongs_to validates the presence of its reference by default already

2023-03-26 22:00 UTC, wJoenn commented on app/models/monument.rb
> +  has_many :favorited_by, through: :favorites, source: :user
monument.favourited_by is not something we need or want, you can remove it

2023-03-26 22:00 UTC, wJoenn commented on app/views/favourites/index.html.erb
> +<% end %>
Please use the same style as Mariana used for the histories#index view

2023-03-26 22:00 UTC, wJoenn commented on config/routes.rb
> +  end
Index and destroy shouldn't be nested

2023-03-26 22:00 UTC, wJoenn commented on db/migrate/20230326202225_create_favorites.rb
> +end
Please rename as CreateFavourites

2023-03-26 22:30 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-26 22:30 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +    end
done

2023-03-26 22:30 UTC, AntonioDannemann commented on app/models/favorite.rb
> +end
done

2023-03-26 22:32 UTC, AntonioDannemann commented on app/models/monument.rb
> +  has_many :favorited_by, through: :favorites, source: :user
done

2023-03-26 22:33 UTC, AntonioDannemann commented on config/routes.rb
> +  end
done

2023-03-26 22:35 UTC, AntonioDannemann commented on db/migrate/20230326202225_create_favorites.rb
> +end
done

2023-03-26 23:11 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-26 23:13 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +    @favourite = current_user.favourites.build(monument: @monument)
done

2023-03-27 14:31 UTC, wJoenn requested changes

2023-03-27 14:31 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  before_action :authenticate_user!
Why do you authenticate_user! ?

2023-03-27 14:31 UTC, wJoenn commented on config/routes.rb
> +  resources :favourites, only: %i[index create destroy]
The create needs to be nested

2023-03-27 14:31 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
This is not how you find an instance of Favourite to destroy it.
There is no monument_id in your params when you destroy

2023-03-27 14:31 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
Please remove everything pundit related.

.build does work but this is not how we traditionnaly initialize a new instance of Favourite.

You don't need an if else if you redirect to the same page anyway, but in case it doesn't save you should render, not redirect

2023-03-27 14:31 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
Please remove everything pundit related.

2023-03-27 14:31 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
The Favourite model doesn't store any data so it's useless to grab it, use favourite_monuments instead

Initializing @favourites 2 times is redundant. Use @user.favourite_monuments.order instead

The query should look for name city and country, not for location

2023-03-27 14:31 UTC, wJoenn commented on app/views/favourites/components/_list.html.erb
> +</div>
Leave the html for the next PR please

2023-03-27 14:31 UTC, wJoenn commented on app/views/favourites/index.html.erb
> +</div>
leave the html for the next PR please

2023-03-27 15:17 UTC, AntonioDannemann commented on app/views/favourites/components/_list.html.erb
> +</div>
done

2023-03-27 15:18 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-27 15:18 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-27 15:20 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-27 18:30 UTC, wJoenn requested changes

2023-03-27 18:30 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
Remove the set_favourite method and do `@favourite = Favourite.find(params[:id])` instead please

2023-03-27 18:30 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
use current_user.favourite_monuments instead of current_user.favourites.includes

The seartch for country instead of country_code

And @favourite_monuments is now a list of Monument so you can remove the join

2023-03-27 18:30 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
@histories doesn't exist

2023-03-27 18:30 UTC, wJoenn commented on app/controllers/favourites_controller.rb
> +  end
Do 
```
@favourite = Favourite.new
@favourite.user  = current_user
@favourite.monument = @monument
``` 
instead

Then if save redirect to monument_path(@monument)
else render "monuments/show"

2023-03-27 18:38 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-27 18:44 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-27 18:47 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done, forgot to change

2023-03-27 18:51 UTC, AntonioDannemann commented on app/controllers/favourites_controller.rb
> +  end
done

2023-03-27 20:46 UTC, wJoenn approved these changes

2023-03-27 20:46 UTC, merged