initial pundit setup completed
wJoenn/artify pull request #23
Opened 2023-03-03 13:32 UTC by Glod33

So the initial setup is done, once a models are finished I will add pundit to it in a PATCH issue/PR.

2023-03-03 13:39 UTC, wJoenn commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
I didn't realize Pundit required Devise before being installed but this is a Devise method and our application does not include Devise yet.
That means we'll have to wait until https://github.com/wJoenn/artify/issues/4 is completed before merging this PR, sorry about that.

2023-03-03 13:39 UTC, wJoenn commented on app/policies/application_policy.rb
> +end
This you edit this file on any way or is this automatically generated ?

2023-03-03 13:41 UTC, wJoenn requested changes

2023-03-03 13:41 UTC, wJoenn commented on app/controllers/application_controller.rb
> +  include Pundit::Authorization
I didn't realize Pundit required Devise before being installed but `authenticate_user` is a Devise method and our application does not include Devise yet.
That means we'll have to wait until https://github.com/wJoenn/artify/issues/4 is completed before merging this PR, sorry about that.

2023-03-03 15:23 UTC, Glod33 commented on app/policies/application_policy.rb
> +end
automatically generated

2023-03-03 15:24 UTC, Glod33 commented on app/controllers/application_controller.rb
> +  include Pundit::Authorization
cool! no problem:)

2023-03-04 09:11 UTC, MarianaCarlota commented on app/policies/application_policy.rb
> +end
I think you ca allready update the show to true since everyone can see the show page

2023-03-04 09:19 UTC, MarianaCarlota commented on app/policies/application_policy.rb
> +end
yeah, you are right. sorry

2023-03-04 09:27 UTC, wJoenn commented on app/policies/application_policy.rb
> +end
There's really no need for an apology Mariana, no worries 🙂

2023-03-04 14:18 UTC, wJoenn approved these changes

2023-03-04 14:18 UTC, merged