updated existing controllers
wJoenn/artify pull request #32
Opened 2023-03-04 18:32 UTC by MarianaCarlota

2023-03-04 18:36 UTC, wJoenn commented
You have some Rubocop issues, can you have a look at the log ?
You can access it by clicking on `Details` in the merge table
![image](https://user-images.githubusercontent.com/75388869/222923077-dbd4ca3a-f38a-4a01-97b7-7bd24da635e0.png)

2023-03-04 18:43 UTC, MarianaCarlota commented
I did. I'm trying to figure out what is wrong

2023-03-04 19:02 UTC, wJoenn requested changes

2023-03-04 19:02 UTC, wJoenn commented on app/controllers/application_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
Can you move the second before_action just after the first one please ?

2023-03-04 19:02 UTC, wJoenn commented on app/controllers/application_controller.rb
> +  end
I think we should permit the photo in the create too because we might just add the profile picture input directly in the registrations new form even if it's not required.

You can also remove both comments in line 11 and 14

2023-03-05 10:43 UTC, MarianaCarlota commented on app/controllers/application_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
done!

2023-03-05 10:43 UTC, MarianaCarlota commented on app/controllers/application_controller.rb
> +  end
and done :)

2023-03-05 10:44 UTC, wJoenn approved these changes

2023-03-05 10:45 UTC, merged