Monuments-controller
wJoenn/artify pull request #44
Opened 2023-03-07 14:51 UTC by Glod33

2023-03-07 16:05 UTC, wJoenn requested changes

2023-03-07 16:05 UTC, wJoenn commented on app/controllers/monuments_controller.rb
> +    end
We don't have a search feature yet.
There's no point in adding that now.

2023-03-07 16:24 UTC, wJoenn commented on app/controllers/monuments_controller.rb
> +  end
You're not using the policy_scope anymore.
And shouldn't you be authorizing the @monument in the show ?

2023-03-07 16:32 UTC, wJoenn requested changes

2023-03-07 16:32 UTC, wJoenn commented on app/models/monument.rb
> +  validates :name, :description, :lat, :lng, :city, :country, :country_code, :photo, presence: true
I just realized but this is not gonna work without the migrations files.
You can't validate the presence of an attribute that isn't part of the db's table.

Do you really need to edit this model for the rest to work ? 🤔 
If not then you can remove that and it'll be updated it my current PR.
If you do need that then copy the migration files from my PR and add them to yours

2023-03-07 16:33 UTC, wJoenn requested changes

2023-03-07 16:33 UTC, wJoenn commented on app/controllers/monuments_controller.rb
> +    @monuments = policy_scope(Monument)
Either one or the other but not both otherwise the value of @monuments is just overwritten

2023-03-07 16:37 UTC, Glod33 commented on app/models/monument.rb
> +  validates :name, :description, :lat, :lng, :city, :country, :country_code, :photo, presence: true
I'll delete the file!

2023-03-07 16:45 UTC, wJoenn requested changes

2023-03-07 16:45 UTC, wJoenn commented on app/policies/monument_policy.rb
> +    end
`show` should be `show?` and outside the scope

2023-03-07 20:00 UTC, wJoenn commented on app/models/monument.rb
> +  validates :name, :description, :lat, :lng, :city, :country, :country_code, :photo, presence: true
You haven't yet

2023-03-07 20:05 UTC, wJoenn requested changes

2023-03-07 20:05 UTC, wJoenn commented on app/policies/monument_policy.rb
> +  end
I asked a TA about this while I we were reviewing my code and he told me that the scope should `scope.all`
Then in the controller you do the near after the scope
`@monuments = policy_scope(Monument).near([user.lat, user.lng], 5)`

2023-03-08 11:45 UTC, wJoenn approved these changes

2023-03-08 11:45 UTC, merged