User html
wJoenn/artify pull request #45
Opened 2023-03-08 00:47 UTC by MarianaCarlota

I have worked mostly on the html. I did a bit of scss but just to try out, nothing final yet. With the colors we have so far, I think something like in the picture below for the _forms could be nice, but with the button in light pink or light green like the colors in the homepage image.
![image](https://user-images.githubusercontent.com/114437310/223589364-f9990f2f-9ef6-44a0-9f4e-399199755ec6.png)
![image](https://user-images.githubusercontent.com/114437310/223589894-1b8242e5-609b-4dbc-a22d-b9161375e770.png)
![image](https://user-images.githubusercontent.com/114437310/223589991-dd35eea3-8e1e-4f79-9751-e94ad6e8f506.png)

2023-03-08 11:45 UTC, Glod33 commented
I personally really like that pinkish color!

2023-03-08 11:56 UTC, Glod33 commented
Also I really like the form you suggest:)

2023-03-08 11:59 UTC, wJoenn commented
The form looks good but that design won't work at all on a mobile screen. It's way too wide.
We could cut it in half and keep the left part only and maybe that would word.

As for the colors, the thing is we don't have a single color yet so don't be fixated on that for now.
The homepage will be what defines the colour palette of our website so until this is done all the colours we choose are just placeholders.
We'll discuss that further at tonight's meeting

2023-03-08 12:02 UTC, wJoenn commented on app/views/devise/passwords/edit.html.erb
> +<%= render "devise/shared/links" %>
This requires an email with a reset password token, which we're not gonna do for now, so you can revert this back to what it was when you generated the Devise:views. We won't use it

2023-03-08 12:31 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +  </div>
Did you copy that from rentart's form ?
You need to remove the `do end` from the label and remove the `onchange` event from the input otherwise the form will submit everytime you add a photo

2023-03-08 12:33 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +  </div>
form-actions is a bootstrap class.
We don't need the div, can you remove it and just leave the button ?

2023-03-08 12:34 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +<div>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %></div>
`method: :delete` should be inside `data:` and be called `turbo_method: :delete`

2023-03-08 12:36 UTC, wJoenn commented on app/views/devise/registrations/new.html.erb
> +  </div>
Same as for Registrations#edit

2023-03-08 12:38 UTC, wJoenn commented on app/assets/stylesheets/components/_form.scss
> +}
Can you leave all the css from this PR and make a new PR later for the css that'll close this issue https://github.com/wJoenn/artify/issues/39 instead ?

2023-03-08 18:38 UTC, MarianaCarlota commented
> 

Yeah, the idea would be to only put the form, not the picture. I will leave it for now untill we have a clearer idea for the design

2023-03-08 18:54 UTC, wJoenn commented
Can you still finish the basic html template ?
I left a few comments that are not design related and that can be adressed

2023-03-08 18:54 UTC, MarianaCarlota commented
Working on it :)

2023-03-08 19:02 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +  </div>
I did. It's corrected now

2023-03-08 20:08 UTC, wJoenn requested changes
You shouldn't have deleted the application.scss nor the _colors.scss, just remove the content you had add to them.
You'll need to restore them as they are in master.

2023-03-08 20:08 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +  </div>
You need to remove the onchange event

2023-03-08 20:08 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +<% end %>
To edit you need the current_password
Also are you not gonna allow the user to edit his current password if he wants to ?

2023-03-08 20:08 UTC, wJoenn commented on app/views/devise/registrations/new.html.erb
> +    </div>
Same, you need to remove the onchange event
Don't forget to try your code everytime you do something.
You would have spotted that immediately after trying to upload a photo in your registration form

2023-03-08 23:20 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +<% end %>
oh, I thought that to change the passoword I would have a form just for it in the password folder

2023-03-08 23:27 UTC, MarianaCarlota commented on app/views/devise/registrations/new.html.erb
> +    </div>
But I did. I tried to upload one photo and I successfully created one account with one photo attached

2023-03-08 23:29 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +<% end %>
That's what I did in rentart but I had to change some Devise's method inside a custom controller for it.
It was a bit of a hassle but I can guide you trhough that later if you're interested.
That'll be for when you do the frontend for the edit page

2023-03-08 23:31 UTC, wJoenn commented on app/views/devise/registrations/new.html.erb
> +    </div>
Strange 🤔 
Normally with that onchange event the form would submit automatically when you upload a picture.
If that wasn't the case for you, I don't understand why it wouldn't but my bad for assuming you didn't test it. Sorry

Still, this shouldn't stay in the code

2023-03-09 19:42 UTC, MarianaCarlota commented on app/views/devise/registrations/new.html.erb
> +    </div>
When I delete it I get this error:
![image](https://user-images.githubusercontent.com/114437310/224136471-cb65b4dc-5bf0-4258-92fc-f33413e4dd2c.png)

2023-03-09 19:50 UTC, wJoenn commented on app/views/devise/registrations/new.html.erb
> +    </div>
That's not related.
Did you add the cloudinary key to your env file ?

2023-03-09 19:56 UTC, MarianaCarlota commented on app/views/devise/registrations/new.html.erb
> +    </div>
I did

2023-03-09 20:40 UTC, wJoenn approved these changes

2023-03-09 20:40 UTC, merged