Monuments index
wJoenn/artify pull request #52
Opened 2023-03-09 12:03 UTC by Glod33

First draft

2023-03-09 12:04 UTC, Glod33 commented
<img width="392" alt="Screenshot 2023-03-09 at 13 03 37" src="https://user-images.githubusercontent.com/112162648/224017787-19733af6-0b14-4935-bf79-a26b9c4570f3.png">

2023-03-09 12:20 UTC, wJoenn commented
I'm really not a fan of using margin and border radius on mobiles.
I think a design like Tripadvisor's would be more fitting
![image](https://user-images.githubusercontent.com/75388869/224021423-17c8a75f-d87f-4bbc-9c51-5c39cf9055fa.png)

2023-03-09 13:09 UTC, wJoenn commented
Here’s another possible inspiration. I like the layout idea but I’m not very found of the card’s appearance
![Uploading 370DA4F7-2562-4DD5-B1C1-49DC233902F3.png…]()

2023-03-09 13:10 UTC, wJoenn commented
Here’s another possible inspiration. I like the layout idea but I’m not very found of the card’s appearance
![C9B7CF01-97CE-495E-991D-12C9B0E14636](https://user-images.githubusercontent.com/75388869/224033132-1a8aa2e3-640a-4cc9-bcdc-629280628820.png)

2023-03-09 13:12 UTC, wJoenn commented
Also I think having a distance from you like
“300m away” or something would be nice

2023-03-09 16:47 UTC, wJoenn commented
Figured google could also be a source pf inspiration
![Uploading 88D46282-4842-41E6-AF13-D736466D1AB0.png…]()

2023-03-09 17:06 UTC, Glod33 commented
<img width="452" alt="Screenshot 2023-03-09 at 18 04 16" src="https://user-images.githubusercontent.com/112162648/224101884-8973fd99-d3e5-4b1a-b2db-5ea59d126c4e.png">

Not too happy with it, what do y'all think?

2023-03-09 21:48 UTC, MarianaCarlota commented
I liked the idea with the photo full width in the screen and semi-tranparent part on the bottom for the text from Louis. Maybe with blue instead of red

2023-03-10 10:59 UTC, Glod33 commented
<img width="521" alt="Screenshot 2023-03-10 at 11 58 20" src="https://user-images.githubusercontent.com/112162648/224299163-bc11818b-412f-471f-af91-9ade3f2615aa.png">

2023-03-10 17:05 UTC, Glod33 commented
I think it's almost ready to push. Just refactoring and removing unnecessary CSS.

I would like to add some more features, but I will do that in a separate issue.

2023-03-10 17:05 UTC, Glod33 commented
<img width="505" alt="Screenshot 2023-03-10 at 18 02 41" src="https://user-images.githubusercontent.com/112162648/224378109-241072b2-c6a4-4f75-be92-e5f3ce25c7ca.png">

2023-03-10 17:43 UTC, Glod33 commented
<img width="579" alt="Screenshot 2023-03-10 at 18 43 03" src="https://user-images.githubusercontent.com/112162648/224386479-e17cd615-eb79-441c-89df-9a0be915ce89.png">

2023-03-11 11:25 UTC, wJoenn requested changes
It would have been better to have a separate branch for the map and the index instead of miwing 2 issues at once.
Please try to keep that in mind for later

2023-03-11 11:25 UTC, wJoenn commented on app/controllers/monuments_controller.rb
> +    end
You're displaying all of the monuments now ?
Not only those around the user ?
Also, the Monuments already have a lat and a lng so you don't need to #geocoded before mapping.
You can just do `@monuments.map { |monument| { lat: monument.lat, lng: monument.lng } }`

The `User.find(144)` is only gonna work for you and not after you reseed or something. Use `.find(name: "Rutger")` instead please

2023-03-11 11:25 UTC, wJoenn commented on app/javascript/controllers/map_controller.js
> +  }
You don't need the parentheses around the parameter in an arrow function when you only have one.
Can you remove them around `marker` in line 22 please ?

2023-03-11 11:25 UTC, wJoenn commented on app/views/layouts/application.html.erb
> +    <link href='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css' rel='stylesheet' />
Can you move these above our css please ?
That way we can overwrite it if we want to.

2023-03-11 11:25 UTC, wJoenn commented on app/views/monuments/index.html.erb
> +  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
Can you send us the API key you used in DM on Slack ?
Is it the same as the previous project ?

2023-03-11 11:25 UTC, wJoenn commented on app/assets/stylesheets/config/_colors.scss
> +$rose: #e7b5aa;
Can you move these further down after the "custom colors" comment ?
The background and rose should already be there

2023-03-12 10:08 UTC, wJoenn requested changes

2023-03-12 10:08 UTC, wJoenn commented on app/assets/stylesheets/components/_index.scss
> +@import "components/containers";
You're already inside the components, you don't need to specify it again

2023-03-12 10:08 UTC, wJoenn commented on app/assets/stylesheets/config/_colors.scss
> +$rose: #e7b5aa;
If I'm not mistaken you have the rose and the background two times and you don't have the navy color anymore

2023-03-12 10:08 UTC, wJoenn commented on app/javascript/controllers/index.js
> +
You can remove the HelloController, the file doesn't exist anymore

2023-03-12 13:12 UTC, wJoenn approved these changes

2023-03-12 13:12 UTC, merged