devise forms first draft
wJoenn/artify pull request #54
Opened 2023-03-11 11:25 UTC by MarianaCarlota

Devise forms. Still want to work on the photo part and the edit page

![image](https://user-images.githubusercontent.com/114437310/224481431-3ce07a6c-3a3b-482d-b591-ff34dd4536ad.png)

![image](https://user-images.githubusercontent.com/114437310/224481472-b760dcdf-fa82-4dc5-9e8e-d3b2eebd22bb.png)

![image](https://user-images.githubusercontent.com/114437310/224481550-90cc5a5f-577e-49d1-80ee-b4fe677ed5d6.png)
![image](https://user-images.githubusercontent.com/114437310/224481569-dcb9356f-b69e-492f-bee3-fada8ccea7ce.png)

2023-03-11 11:42 UTC, wJoenn commented
Can you try dealing with the file input again before we merge please ?
The trick is to hide the input by giving it a display of none and to use the label to select the file instead of the input.
Labels can be used to select the fields, try clicking on "Photo" and you'll see it works the same as if you clicked on "Choose file"

The camera button is a form with a file input for example but the only thing you see is the label in the form of a button with a camera icon.

There's also a way to show the uploaded image if you want, that's a bit more advanced and require Javascript but you can look at Rentart's code fi you wanna try it, I did it for the Arts#new form

2023-03-11 12:52 UTC, MarianaCarlota commented
Ok, Thank you.
I will leave it for now like this and this afternoon I will try to improve it with the photo and all

![image](https://user-images.githubusercontent.com/114437310/224485549-aaaa1925-e2bc-46b2-b35e-3c5b255c3f90.png)

2023-03-12 12:52 UTC, wJoenn commented on app/views/devise/sessions/new.html.erb
> +        </div>
What is this ?

2023-03-12 13:06 UTC, MarianaCarlota commented on app/views/devise/sessions/new.html.erb
> +        </div>
It gives password visibility to the user when he is logging in if he wants to check if the password is correctly typed

2023-03-12 13:09 UTC, wJoenn commented on app/views/devise/sessions/new.html.erb
> +        </div>
Where is it coming from ?
Is it a Devise thing ?
What's the `t` method ?
Where are these class names coming from ? `class: "form__label form__label--login_color form__label--position"`

2023-03-12 17:13 UTC, MarianaCarlota commented on app/views/devise/sessions/new.html.erb
> +        </div>
https://mirrorcommunications.com/blog/allow-users-to-hide-and-show-their-password-with-stimulus-js

2023-03-12 17:14 UTC, MarianaCarlota commented on app/views/devise/sessions/new.html.erb
> +        </div>
I took it from this website and it's working

2023-03-12 17:16 UTC, MarianaCarlota commented on app/views/devise/sessions/new.html.erb
> +        </div>
![image](https://user-images.githubusercontent.com/114437310/224561001-404868e0-07eb-457b-a95c-6c493dab8f75.png)
![image](https://user-images.githubusercontent.com/114437310/224561038-c6c19992-caa5-42c5-8d0e-698179028571.png)

2023-03-12 17:28 UTC, MarianaCarlota commented on app/views/devise/sessions/new.html.erb
> +        </div>
I triyed without the  t method and those classes and it workes the same. It's removed now from the file.

2023-03-12 17:50 UTC, wJoenn requested changes

2023-03-12 17:50 UTC, wJoenn commented on app/assets/stylesheets/components/_button.scss
> +  }
hover effect don't exist on mobile so you can remove this

2023-03-12 17:50 UTC, wJoenn commented on app/assets/stylesheets/components/_form.scss
> +  }
Same for this, it's empty anyway

2023-03-12 17:50 UTC, wJoenn commented on app/assets/stylesheets/components/_form.scss
> +}
An empty line is missing between 121 and 122

2023-03-12 17:50 UTC, wJoenn commented on app/assets/stylesheets/components/_form.scss
> +  }
Do
```
p a {
  color: $rose;
}
```
instead please

2023-03-12 17:50 UTC, wJoenn commented on app/assets/stylesheets/components/_form.scss
> +    }
Same for this, no hover on mobile

2023-03-12 17:50 UTC, wJoenn commented on app/assets/stylesheets/config/_setup.scss
>  }
This is supposed to be very general container.
If you want to have a bottom padding of 80px then assign this proprety to another element please.
Your form for example

2023-03-12 17:50 UTC, wJoenn commented on app/views/devise/sessions/new.html.erb
> +          </div>
Can you use one of these icons to show and hide instead of a text perhaps ?
![image](https://user-images.githubusercontent.com/75388869/224562175-cb5f1648-7625-4c53-b053-087354622c62.png)

Also why are you using a `a` if you're not redirecting to anything ? Just remove the `a` and use the `p` instead

2023-03-12 17:50 UTC, wJoenn commented on app/javascript/controllers/toggle_controller.js
> +  static targets = ["show", "unhide"];
Show and unhide mean the same thing.
Call them button and input instead please

2023-03-12 17:50 UTC, wJoenn commented on app/javascript/controllers/index.js
> +
Rename this ToggleHiddenPassword please

2023-03-12 17:50 UTC, wJoenn commented on app/javascript/controllers/toggle_controller.js
> +  }
Why do you have these if you already have static targets ?

2023-03-12 17:50 UTC, wJoenn commented on app/javascript/controllers/toggle_controller.js
> +  }
Rename this toggleHiddenPassword please

Then do this inside the method instead. If you don't understand feel free to ask

```
toggleHiddenPassword() {
   this.inputTarget.textContent = this.buttonTarget.classList.include("fa-eye") ?  "show" : "hide"
   
   this.buttonTarget.classList.toggle("fa-eye")
   this.buttonTarget.classList.toggle("fa-eye-slash")
}
```

2023-03-12 19:47 UTC, MarianaCarlota commented on app/assets/stylesheets/components/_form.scss
> +    }
I put this here so the user know wich field of the form is selected for him to write

![image](https://user-images.githubusercontent.com/114437310/224569341-907b6633-4c48-46b0-899c-acef277c9ab7.png)

2023-03-12 20:00 UTC, wJoenn commented on app/assets/stylesheets/components/_form.scss
> +    }
My bad I misread and thought it was a hover effect

2023-03-12 20:26 UTC, MarianaCarlota commented on app/views/devise/sessions/new.html.erb
> +          </div>
I tried to put aan icon on it but was having troubles with it. I will give it another try

2023-03-12 20:40 UTC, MarianaCarlota commented on app/javascript/controllers/toggle_controller.js
> +  }
without it it doesn't work and I get this error:
![image](https://user-images.githubusercontent.com/114437310/224572255-944e354c-8d2d-4904-b4d8-37ae3263fd3f.png)

2023-03-12 20:59 UTC, MarianaCarlota commented on app/assets/stylesheets/components/_button.scss
> +  }
This is ment to happen when the user clicks on the button. The button gets a bit smaller to give a since of depth as if the user was really clicking on something. Is there another effect on css I can use for clicking? Or maybe with javascript?

2023-03-12 22:06 UTC, wJoenn requested changes

2023-03-12 22:06 UTC, wJoenn commented on app/assets/stylesheets/components/_button.scss
> +  }
When you click on the button it should be reloading the page and displaying an alert that says "Your account was updated" or something like that, no ?
That means that the hover effect wouldn't be displayed unless I'm mistaken.
Can you maybe share a video of what it looks like ?

2023-03-12 22:06 UTC, wJoenn commented on app/javascript/controllers/toggle_hidden_password_controller.js
> +}
Have you tried the way I reccomended ?

2023-03-12 22:06 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +      <p><%= f.label :first_name %></p>
Why are all of these inside a p tag now ?

2023-03-12 22:06 UTC, wJoenn commented on app/views/devise/sessions/new.html.erb
> +            <p class="show" data-toggle-hidden-password-target="button" data-action="click->toggle-hidden-password#password"><i class="fa-regular fa-eye"></i></i></p>
Have you considered just using the icon instead of having a p tag ?

2023-03-12 22:11 UTC, wJoenn commented on app/javascript/controllers/toggle_controller.js
> +  }
Can you show me your code when you get this error ?

2023-03-12 22:39 UTC, MarianaCarlota commented on app/views/devise/registrations/edit.html.erb
> +      <p><%= f.label :first_name %></p>
is to upcase the letters make the color semi transparent. The labels text was too bright before

2023-03-12 22:55 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +      <p><%= f.label :first_name %></p>
Why don't you change the css of the label directly then ?

2023-03-13 00:01 UTC, wJoenn approved these changes

2023-03-13 00:02 UTC, merged