Featured card new design
wJoenn/artify pull request #63
Opened 2023-03-12 17:01 UTC by wJoenn

![image](https://user-images.githubusercontent.com/75388869/224560182-514d789c-92ce-4d97-84d7-e9d6ae306f0d.png)

2023-03-12 22:21 UTC, MarianaCarlota commented
I would drop the title a bit more down or start the blue gradient a bit more up so the text doesn't mix so much with the background and it's easier to read

2023-03-12 22:22 UTC, MarianaCarlota requested changes

2023-03-12 22:22 UTC, MarianaCarlota commented on app/assets/stylesheets/components/_card.scss
> +      transform: skew(-20deg);
I feel there is few constrast between the text color and the background on the button.  Can you try the text color $secondary to see if is more readable?

2023-03-12 22:31 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +      transform: skew(-20deg);
I tried it and it definitely is more readable.
I wasn't sure about the looks though
![image](https://user-images.githubusercontent.com/75388869/224577811-de5cfa98-d43a-4dd7-8f3d-8b6987faf9a0.png)

2023-03-12 22:53 UTC, wJoenn commented
https://user-images.githubusercontent.com/75388869/224578768-9b9438a8-543c-48f3-819e-b6c5798ac8bd.mp4

2023-03-12 23:07 UTC, MarianaCarlota commented
ok, increasing the text shadow is a good idea :)

2023-03-13 18:29 UTC, Glod33 commented
Looks cool!

2023-03-13 19:26 UTC, MarianaCarlota approved these changes

2023-03-13 19:26 UTC, merged