Devise alerts
wJoenn/artify pull request #70
Opened 2023-03-15 00:14 UTC by MarianaCarlota

The js is working but I still need to fix one thing: The alerts are creating a space on the top of the screan.

https://user-images.githubusercontent.com/114437310/225170237-31f3856f-0304-4731-8fba-bf5f497718d0.mp4

![image](https://user-images.githubusercontent.com/114437310/225170277-c389434c-277a-4032-a25b-d19e310cb06b.png)

2023-03-15 07:39 UTC, wJoenn commented
Try giving them a `position: fixed`, `top: 0`, `z-index: 10`

2023-03-15 22:45 UTC, wJoenn requested changes
I'd like the alert to be a bit faster.
I think 1 second is more than enough for the transition and I would say not more than 3s before it disappears

2023-03-15 22:45 UTC, wJoenn commented on app/assets/stylesheets/config/_setup.scss
>  }
If you wanna add a padding-bottom to your div please do that somewhere else than in this container selector.
We don't want all the containers to have a padding-bottom of 80px

2023-03-15 22:45 UTC, wJoenn commented on app/views/devise/registrations/edit.html.erb
> +
This should be somewhere else, not in the edit.
It'll be easier for us to have one until we have a place for it but keep in mind that we'll remove this one later

2023-03-15 22:45 UTC, wJoenn commented on app/views/layouts/application.html.erb
>      <p class="alert"><%= alert %></p>
You need to remove those comments

2023-03-15 22:45 UTC, wJoenn commented on app/javascript/controllers/flashes_controller.js
> +    this.elementTarget.classList.add("hidden");
Your elements already have a class of hidden, do you really need to add it a second time ?

2023-03-15 22:45 UTC, wJoenn commented on app/javascript/controllers/flashes_controller.js
> +    if (this.elementTarget.classList.contains("hidden")) {
Same here, it should always been hidden when I look at your code so you don't need that condition.

2023-03-15 22:45 UTC, wJoenn commented on app/assets/stylesheets/components/_flash.scss
> +  z-index: 300;
300 is exagerated 😄 
Set it to 30 instead please, that way it'll still be under the loading logo page
Also I think you can remove the translateY(0) as this is default behaviour
The font should already be $body-font too

2023-03-15 22:45 UTC, wJoenn commented on app/assets/stylesheets/components/_flash.scss
> +}
You already have the transition in the other class so you don't need it a second time

2023-03-15 22:45 UTC, wJoenn commented on app/assets/stylesheets/components/_index.scss
> +@import "flash";
form and button already exists, why add them a second time ?

2023-03-16 00:15 UTC, MarianaCarlota commented on app/assets/stylesheets/config/_setup.scss
>  }
It was just to make sure that no info at the bottom of the page would be covered by the navbar. It's removed now.

2023-03-16 14:13 UTC, wJoenn commented on app/javascript/controllers/flashes_controller.js
> +    }
If I'm not mistaken the element's classList should always be containing hidden so I think the if condition here is not necessary. Can you try removing it to see if it works ? 🤔

2023-03-16 14:13 UTC, wJoenn commented on app/assets/stylesheets/components/_flash.scss
> +}
I was wondering if you could try a 1second transition and a 3seconds timeout in the js controller because I think the animation is too slow at the moment. Did you try that ?

2023-03-16 20:44 UTC, merged