index redone
wJoenn/artify pull request #81
Opened 2023-03-17 18:28 UTC by Glod33

2023-03-17 22:18 UTC, wJoenn requested changes

2023-03-17 22:18 UTC, wJoenn commented on app/assets/stylesheets/components/_button.scss
> +  z-index: 1;
If it's always gonna be at the top left corner of the screen then you don't need it to be absolute from the Parent.
You can set this as position: fixed instead and remove the position relative of the parent element.

Can you also use a z-index of 10 instead of 1 ? We've been using indexes by ten until now

2023-03-17 22:18 UTC, wJoenn commented on app/javascript/controllers/map_controller.js
> +      new mapboxgl.Marker({ "color": "#9ab495" }).setLngLat([marker.lng, marker.lat]).addTo(this.map)
Do you need to specify the color here if you've already done so in the css ?
You should probably remove the path's color from the css imo

2023-03-17 22:18 UTC, wJoenn commented on app/views/monuments/index.html.erb
> +        <% end %>
This is not indented proprely

2023-03-17 22:18 UTC, wJoenn commented on app/views/monuments/index.html.erb
> +          <div class="monument-index-overlay">
this is not indented proprely

2023-03-17 22:18 UTC, wJoenn commented on app/views/monuments/index.html.erb
>            </div>
Please don't use style inside html unless it's required.
Were you not gonna use the same style from as the homepage's cards ?

Also it's not indented proprely

2023-03-17 22:18 UTC, wJoenn commented on app/assets/stylesheets/components/_card.scss
> +    }
Were you not gonna use the same style as the homepage's cards ?

2023-03-18 10:24 UTC, Glod33 commented on app/views/monuments/index.html.erb
>            </div>
I only need a display flex on this one, I thought it would be a bit much to make a whole class for it

2023-03-18 11:41 UTC, wJoenn approved these changes

2023-03-18 11:45 UTC, merged